name: Update V2Ray Subscription

on:
  schedule:
    # Every 5 minutes (Note: GitHub may not execute exactly every 5 minutes but approximately)
    - cron: "*/5 * * * *"
  workflow_dispatch: {}  # Manual trigger for testing

jobs:
  update-sub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch subscription content
        run: |
          # Set your subscription URL here
          SUB_URL="https://manager.farsonline24.ir/"
          curl -fsSL "$SUB_URL" -o sub_raw.txt

      - name: Encode to Base64
        run: |
          # Convert entire sub_raw.txt content to Base64
          base64 -w0 sub_raw.txt > sub_base64.txt

      - name: Move to final path
        run: |
          # Move final file to public folder
          mkdir -p public
          mv sub_base64.txt public/sub.txt
          rm -f sub_raw.txt

      - name: Commit changes
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: actions@github.com
        run: |
          git status
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add public/sub.txt
          git commit -m "Update subscription $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || exit 0
          git push